### ISSUE TITLE
Color stop interval clarification?

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/colr-gradients-spec#281] opened 2021-04-27 08:24 UTC
I'm reading this over and over and I can't make sense of it:

> For example, a gradient color line could be defined with two color stops at 0.2 and 1.5. The gradient color line is positioned in the design grid by aligning stop offsets 0 and 1 to design grid positions, as defined for each gradient type, using an extrapolated color of stop offset 0 at one position and an interpolated color of stop offset 1 at the other position. Colors for offsets between 0.5 and 1.5 are interpolated. Colors for offsets above 1.5 and below 0.2 are defined and determined by the color line’s extend mode, described below.

(I think "0.5" should be "0.2".)

From the above, I truly don't understand what the intended behavior is for the example.

If I feed such values to Cairo, Skia, or write it in an SVG image (drawing a linear gradient), I observe the following among the three:
- Values outside of the [0, 1] interval appear to be clamped to [0, 1]
- Extending happens on the [0, 1] interval, regardless of the min/max stop offset values
- If the first stop offset is greater than zero, that color extends to the interval [0, firstStopOffset], *regardless of extend mode*
- Likewise, if the last stop offset is less than one, the last color extends to [lastStopOffset, 1], *regardless of extend mode*
- One exception: in Cairo, the above two behave differently in REPEAT mode (could that be a bug?), but is otherwise consistent with Skia and SVG for PAD and REFLECT.

What is the intention of the COLRv1 stop offsets when the total interval is not [0, 1]? Should it match the popular 2D platforms?

**Comment by behdad** [comment] 2021-04-27 22:39
The text you quoted is indeed bad.

The way we designed is, it is more generic and useful than the graphics library do, but is convertible to those. This is how it was intended:

Take the min/max stop positions and extend both ways towards infinity according to the extend mode. For PAD, the first and last are extended to -/+ inifinity. For REPEAT, the region between min/max is perpetually repeated in both directions. For REFLECT, the invert of the internal is appended on one end, and the resulting larger interval repeated in both directions.

So now you have a color-line that is well-defined for any input scalar number. Position the color-line on the graphics primitive such that the gradient's two points refer to the positions 0.0 and 1.0 on the color line. The colorline now specifies the color of the entire to infinity.

**Comment by justvanrossum** [comment] 2021-04-28 05:16
Thanks, it makes perfect sense now! So we pretty much refit the stop offsets from [min,max] to [0,1].

**Comment by justvanrossum** [comment] 2021-04-28 06:59
Btw. I don't see this happening in the current Skia or FreeType COLRv1 implementations, and neither do I see the prescribed "sort by color stop offset". @drott, am I missing something?

**Comment by justvanrossum** [comment] 2021-04-28 07:25
> So we pretty much normalize the stop offsets from [min,max] to [0,1]

Hm, rereading what you wrote, this must be wrong.

I understand your definition of the color line, but now:

> Position the color-line on the graphics primitive such that the gradient's two points refer to the positions 0.0 and 1.0 on the color line

Do I understand correctly that we need to recalculate the points for linear gradients like this:

firstPoint = (0, 0)
secondPoint = (100, 0)
(ignoring the third point, for the example let's assume it's perpendicular to the main line)
for colorStops [0, 1] they stay the same
for colorStops [0.2, 1] they become (20, 0) and (100, 0)
for colorStops [-0.2, 1] they become (-20, 0) and (100, 0)
for colorStops [0, 0.8] they become (0, 0) and (80, 0)
for colorStops [0, 1.2] they become (0, 0) and (120, 0)
etc.

How's that?

**Comment by drott** [comment] 2021-04-28 07:36
> Btw. I don't see this happening in the current Skia or FreeType COLRv1 implementations, and neither do I see the prescribed "sort by color stop offset". @drott, am I missing something?

Which is it that you don't see in the Skia implementation? Can you quote which part of the spec you mean by  "sort by color stop offset"?

> Do I understand correctly that we need to recalculate the points for linear gradients like this before we send them to the library:

I depends on how the library handles what happens at the extremes and whether it requires you to set values for the control vector (as cairo calls it) 0 and 1 positions. It might be possible to configure the control vector consisting of p0 and p1, and then set the first color stop at 0.2, i.e. without explicitly defining a 0 or 1 color stop position, or without moving the points.

**Comment by justvanrossum** [comment] 2021-04-28 07:43
Sorting:

> Applications shall apply the colorStops in increasing stopOffset order. The stopOffset value uses a variable structure and, with a variable font, the relative orderings of ColorStop records along the color line can change as a result of variation. With a variable font, the colorStops shall be ordered after the instance values for the stop offsets have been derived.

> Which is it that you don't see in the Skia implementation?

If I understand the FT and Skia source correctly, it recalculates the second point based on the first point, but nothing more. And it passes the color stop offsets from the font to `SkGradientShader::MakeLinear` unchanged. Do I see that right?

**Comment by drott** [comment] 2021-04-28 08:01
> If I understand the FT and Skia source correctly, it recalculates the second point based on the third point, but nothing more. 

Yes, it calculates a new second point based on the transformation that is controlled by p2.

> And it passes the color stop offsets from the font to SkGradientShader::MakeLinear unchanged. Do I see that right?

Yes, from which the stop sorting is missing - contrary to what I was expecting, passing non increasing stop offsets to Skia is not automatically handled and [leads to unexpected results](https://fiddle.skia.org/c/95a6221ecee0249b597179be6c1c5f97). Filed [Skia issue 11921](https://bugs.chromium.org/p/skia/issues/detail?id=11921 )

**Comment by justvanrossum** [comment] 2021-04-28 08:09
Hm, but Skia behaves differently than how I read Behdad's description, in that reflect/repeat uses [0, 1], and values outside the [0, 1] range are clamped:
- https://fiddle.skia.org/c/32773b1237b360307fac2d3fd3146ad0

(I could still be misunderstanding the spec's intention, though.)

**Comment by drott** [comment] 2021-04-28 08:18
Playing with the fiddle, it seems Skia uses 0 to max for the repeat, and in that sense there is probably a bug in the impl and we would need to shift p0 similar to your examples in https://github.com/googlefonts/colr-gradients-spec/issues/281#issuecomment-828215868. The spec's intention is to start repeating/reflecting outside min/max.

**Comment by justvanrossum** [comment] 2021-04-28 08:20
> it seems Skia uses 0 to max for the repeat

That's not what I observe: any max greater than 1 does not change the image for me.

**Comment by drott** [comment] 2021-04-28 08:22
It's true, that's not entirely it - but if I use `SkScalar stops[4] = { 0.9, 100};` I still get some red https://fiddle.skia.org/c/0721dea7b15af5994c4959a95fcb1243 - need to look into it. But I hope the spec's intent is clear?

**Comment by justvanrossum** [comment] 2021-04-28 08:37
> It's true, that's not entirely it - but if I use SkScalar stops[4] = { 0.9, 100}; I still get some red

Yes, that's because (I think) the 100 gets clamped to 1.

> But I hope the spec's intent is clear?

I think so.

**Comment by justvanrossum** [comment] 2021-04-28 10:30
Let's see if I got this right.

The following images show a linear gradient in repeat mode. The black lines represent p0 and p1, their direction represents (p0,p2).

`stopOffsets = [0, 1]`
![skia_colorStops_REPEAT_0_1](https://user-images.githubusercontent.com/4246121/116388754-775bfd00-a81c-11eb-9b93-5266334cefde.png)

`stopOffsets = [0.2, 0.8]`
![skia_colorStops_REPEAT_0 2_0 8](https://user-images.githubusercontent.com/4246121/116388776-7b881a80-a81c-11eb-900f-c0229ff50c93.png)

`stopOffsets = [0, 1.5]`
![skia_colorStops_REPEAT_0_1 5](https://user-images.githubusercontent.com/4246121/116388799-8478ec00-a81c-11eb-968a-5da4f0996447.png)

`stopOffsets = [0.5, 1.5]`
![skia_colorStops_REPEAT_0 5_1 5](https://user-images.githubusercontent.com/4246121/116388818-88a50980-a81c-11eb-853b-3f0cfbf5f49d.png)

**Comment by drott** [comment] 2021-04-28 11:01
Yes, looks good to me, that's what it's supposed to look like.

**Comment by justvanrossum** [comment] 2021-04-28 11:38
Thanks.

I think this implies that the current Skia behavior is correct in only these cases:
- pad: min/max stop offset is within [0, 1]
- repeat/reflect: min/max stop offset is exactly [0, 1]

**Comment by davelab6** [comment] 2021-04-30 20:22
> I'm reading this over and over and I can't make sense of it:

What kind of spec text change could improve this?

**Comment by justvanrossum** [comment] 2021-04-30 20:28
> What kind of spec text change could improve this?

The thing that confused me the most was

> using an extrapolated color of stop offset 0 

I think that's wrong: colors never get extrapolated.

I don't really know — @horasio did get the correct meaning from the text, so perhaps it's just me being a bad reader. What would have helped me tremendously is an illustration.

**Comment by justvanrossum** [comment] 2021-04-30 20:33
Illustrations and pseudo code.

**Comment by PeterConstable** [comment] 2021-06-02 19:49
>I think that's wrong: colors never get extrapolated.

Indeed, that was badly worded. I think revised wording will fix this.

**Comment by PeterConstable** [comment] 2021-06-03 18:50
Fixed by #292 and #296

**Closed by PeterConstable** 2021-06-03 18:50 UTC
