### ISSUE TITLE
Painting certain layers above all other layers

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/colr-gradients-spec#280] opened 2021-04-26 16:16 UTC
I’m not sure of this is in scope of COLRv1, but one of the issues of COLRv0 is the inability to paint layers in a certain order across the glyph string not just for each individual glyph.

Suppose we have overlapping glyphs ABC each has one color layer. Current rendering would A, then B covering parts of A, then C covering parts of B (or the reverse for RTL text, depends on the graphics stack). But if we want B to be painted over e both A and C, there is no way to do that. AFAICT, COLRv1 does not currently address this, right?

See https://twitter.com/PhDniX/status/1386656549444202496 for a real words example of this issue (I’m sure there are more).

**Comment by Lorp** [comment] 2021-04-26 16:42
You are correct: this issue is not addressed in COLRv0, COLRv1 or OpenType-SVG.

There have been strong expressions of how useful it would be be for colour fonts, from Georg Seifert @schriftgestalt and others. For example, neither connecting scripts nor shadow effects are possible without careful restrictions, significantly limiting creative possibilities.

Unfortunately the consensus seems to be that implementation in rendering systems and apps requires too much reengineering for it to be feasible.

**Comment by Lorp** [comment] 2021-04-26 17:07
Even if there is the will, a solution will be quite difficult to specify. How should adjacent lines of text interact? We probably need to work on entire text containers, not just on text runs. Also, how are the “equivalent” layers between glyphs to be identified? What happens if “equivalent” layers have different layer effects? Should overlapping transparent layers be merged before applying transparency (like in a connecting script) or after (to implement optical effects)? IMO advocates need to prototype fonts and behaviour before this goes further.

**Comment by behdad** [comment] 2021-04-26 17:46
All of what Laurence said...

We can add a z-order to layers and let browsers create layers using them. But that would be a separate initiative than COLRv1.

**Comment by rsheeter** [comment] 2021-05-07 05:05
Closing as duplicate of #199; please reopen if I've misunderstood and that is not the case.

> Unfortunately the consensus seems to be that implementation in rendering systems and apps requires too much reengineering for it to be feasible.

COLR v1 is designed to be relatively easy to implement - we cherry-picked graphic constructs that are widely supported - so on that basis alone this doesn't fit COLR v1.

If I put my optimistic hat on I would say if we ship COLR v1 and it gains wide adoption the case to go deeper in the future could be stronger. I realize this is a real problem and that's an entirely unsatisfactory answer.

**Closed by rsheeter** 2021-05-07 05:05 UTC
