### ISSUE TITLE
Use 32-bit glyph IDs

### ISSUE THREAD

**Issue by Lorp** [googlefonts/colr-gradients-spec#95] opened 2020-11-06 23:36 UTC
Consider using 32-bit glyph IDs throughout COLRv1, so that the format may be reused intact in the future font formats that are being considered.

**Comment by drott** [comment] 2020-11-09 14:18
Duplicate of #8 - we closed it there with the intention of treating this as a standalone update to OFF.

**Closed by drott** 2020-11-09 14:18 UTC
