### ISSUE TITLE
Description of the VarF2Dot14 needs review

### ISSUE THREAD

**Issue by vlevantovsky** [googlefonts/colr-gradients-spec#197] opened 2021-01-04 03:09 UTC
The last paragraph of the VarF2Dot14 description says:

> If the context in which the VarF2Dot14 is used contrains the valid range for the default value, then any variations by applying deltas are clipped to that range.

Possible spelling correction for "contrains" could be either "contains" or "constrains" - I am not sure what the original intent was and which one is appropriate in this case.

**Comment by PeterCon** [comment] 2021-01-04 19:05
In this case "constrains" was intended.

**Comment by PeterConstable** [comment] 2021-01-12 18:49
Fixed by #198

**Closed by PeterConstable** 2021-01-12 18:49 UTC
